# nome_da_lore= "A era do dragão de gelo"
# nome_do_dragão= "Hyo"
# "Há muito tempo, em uma pacata vila, havia, não muito longe de lá, uma caverna onde vivia uma criatura"
# "Esta criatura era bastante temida pela vila, todos tinham medo que ela acordasse"
# "um certo dia, toda a vila foi soterrada por uma terrível tempestade"
# "todos ficaram espantados e cheios de terror, ninguém sabia o porquê daquilo"
# "um dia, um garoto chamado Victor"
# "aula 5"
# idade= 7000

# nome_da_lore= "A era do dragão de gelo"
nome_do_dragao= "Hyo"
nome_do_prota= "Victor"
historia= "Há muito tempo, em uma pacata vila, havia, não muito longe de lá, uma caverna onde vivia uma criatura"
historia= historia+ f" Esta criatura chamavasse {nome_do_dragao} era bastante temida pela vila, todos tinham medo que ela acordasse"
historia= historia+ f" um certo dia, toda a vila foi soterrada por uma terrível tempestade"
historia= historia+ f" todos ficaram espantados e cheios de terror, ninguém sabia o porquê daquilo"
historia2= f"Um dia, um garoto chamado {nome_do_prota} simplesmente BROTOU na vila, ele estava confuso (o mlk acabou de cair do céu, ÓBVIO que ele estaria confuso)"
historia2= historia2+ f". Após um tempo se recuperando, {nome_do_prota} acabou ouvindo sobre a terrível criatura que habitava na caverna e também sobre a"
historia2= historia2+ f" estranha aparição da tempestade de neve que assolou aquela vila e a deu tempos de extremo frio,"
historia3= f"então, movido pela curiosidade, {nome_do_prota} foi em direção da misteriosa caverna em busca de respostas"
